version: "3.7"
services:
  envoy:
    container_name: envoy
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "9901:9901"
  webclient-react:
    container_name: react-ts
    build:
      context: ./webclient
      dockerfile: Dockerfile
    depends_on:
      - webserver-go
    volumes:
      - './webclient:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    stdin_open: true
  webserver-go:
    container_name: webserver-go
    build:
      context: ./webserver
      dockerfile: Dockerfile
    depends_on:
      - dgraph-alpha
      - dgraph-zero
      - envoy
    volumes:
      - './webserver:/app'
    ports:
      - "9090:9090"
    restart: on-failure
    #command: go run main.go
# dgraph services: https://dgraph.io/blog/post/building-todo-list-react-dgraph/
  dgraph-zero:
    container_name: dgraph-zero
    image: dgraph/dgraph:v20.03.2
    hostname: "dgraph-zero"
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    #restart: on-failure
    command: dgraph zero --my=dgraph-zero:5080

  dgraph-alpha:
    container_name: dgraph-alpha
    image: dgraph/dgraph:v20.03.2
    hostname: "dgraph-alpha"
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    #restart: on-failure
    command: dgraph alpha --my=dgraph-alpha:7080 --lru_mb=2048 --zero=dgraph-zero:5080

  dgraph-ratel:
    container_name: dgraph-ratel
    image: dgraph/dgraph:v20.03.2
    hostname: "dgraph-ratel"
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel

volumes:
  dgraph:
