#!/bin/bash

SERVER="webserver/cmd"
CLIENT="webclient/src"

protoc protos/hello/hello.proto --go_out=plugins=grpc:$SERVER
protoc protos/dgraph/dgraph.proto --go_out=plugins=grpc:$SERVER
protoc protos/hello/hello.proto --js_out=import_style=commonjs:$CLIENT --grpc-web_out=import_style=typescript,mode=grpcwebtext:$CLIENT
protoc protos/dgraph/dgraph.proto --js_out=import_style=commonjs:$CLIENT --grpc-web_out=import_style=typescript,mode=grpcwebtext:$CLIENT

# automatically disable eslint on the generated js file, otherwise, it will not compile
eslint_disable() {
	FPATH=$(find . -name "*pb.js" -not -path "*node_modules*")
	sed -i '1i/*eslint-disable*/' $FPATH
}

eslint_disable
